micronaut:
  application:
    name: crud
  server:
    cors:
      enabled: true
    port: 8080
    cassandra:
      default:
        basic:
          contact-points:
            - "127.0.0.1:9042"
            - "5.6.7.8:9042"
          session-keyspace: ${KEYSPACE:mykeyspace}
          load-balancing-policy:
            local-datacenter: ${DATACENTER:datacenter1}
cassandra:
  default:
    clusterName: '"myCluster"'
    contactPoint: '"localhost"'
    port: 9160
    maxSchemaAgreememtWaitSeconds: 20
    ssl: true
endpoints:
  health:
    enabled: true